version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
    command: node .output/server/index.mjs
    restart: on-failure
    networks:
      - service-network
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - service-network
  mysqldb:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=dyploma_db_new
    ports:
      - 3307:3306
    networks:
      - service-network
    volumes:
      - db:/var/lib/mysql
  backend:
    depends_on:
      - mysqldb
    build:
      context: ../Backend
      dockerfile: Dockerfile
    image: backend:latest
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{ "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/dyploma_db_new", "spring.datasource.username" : "root", "spring.datasource.password" : "123456", "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver", "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect", "spring.jpa.properties.hibernate.globally_quoted_identifiers" : "true", "spring.jpa.hibernate.ddl-auto" : "update"}'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - service-network
networks:
  service-network:
    driver: bridge
volumes:
  db:
